version: "3"

services:
  db:
    image: mongo
    container_name: db
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root

  server:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: server
    depends_on:
      - db
    ports:
      - 8080:8080